name: wind-mamba
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.9.25
  - numpy=1.26.4
  - pandas=2.3.3
  - scikit-learn=1.1.3
  - scipy=1.13.1
  - matplotlib=3.9.4
  - tqdm=4.67.1
  - pytorch=2.8.0
  - pytorch-cuda=12.8
  - pip
